all:
	s3cmd -P sync core s3://cdn.plweb.org/plwebstart/
	s3cmd -P sync libs s3://cdn.plweb.org/plwebstart/
	s3cmd -P sync plugins s3://cdn.plweb.org/plwebstart/
	s3cmd -P sync swt s3://cdn.plweb.org/plwebstart/

